spring.application.name=jarvis-medical-ai

google.api.key=AIzaSyAyFmyegNfxLf0H5vFLoXl4fs-mBS-gEog
jarvis.ai.brain.model=gemini-3-flash
jarvis.ai.voice.api-key=AIzaSyCkEk4e9phJWFWZA0_RUuzOeaCJK75015g
server.port=8084

spring.datasource.url=jdbc:postgresql://ep-silent-mouse-am5qod81-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9qgSCXE0Jbjp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect